title: Yuzhi Chen
# tagline: Here is personal website of Yuzhi Chen.
# description: Two roads diverged in woods, I took the one less traveled by.
#Comment out url when working locally to resolve base urls correctly
url: https://FengHY-Chen.github.io

# Owner/author information
owner:
  name: Yuzhi Chen
  avatar: yuzhi.jpg
  # bio: Two roads diverged in woods, I took the one less traveled by.
  email: y.z.chen.fhy@gmail.com
  orcid: https://orcid.org/0000-0003-2321-993X
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  #twitter: lancecai2002
  github: FengHY-Chen
  #linkedin: hanlincai
  scholar: https://scholar.google.com/citations?view_op=list_works&hl=zh-CN&user=bxzoBQkAAAAJ
  #bilibili: 594030035
  researchgate: https://www.researchgate.net/profile/Yuzhi-Chen-3
  #zhihu: https://www.zhihu.com/people/chlire
  # facebook: 
  # instagram: 
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

  Page Views: <span id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</span>
  Unique Visitors: <span id="busuanzi_container_site_uv">访客数<span id="busuanzi_value_site_uv"></span>人</span>
# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: Yuzhi Chen
    url: /
  - title: Publications
    url: /publications/
  - title: Awards
    url: /awards/
  - title: News
    url: /news/
  - title: Sources
    url: /sources/
  - title: Activities
    url: /activities/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Nanjing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false



include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

<script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
# Latest update in 2024/06/01 by Yuzhi Chen.